### ISSUE TITLE
trouble using search_issues

### ISSUE THREAD

**Issue by mkauzlar** [frimicc/jira-client-automated#14]
Hello,
I'm unable to get search_issues work with the $fields option as in:
my @search_results = $jira->search_issues($jql, 1, 100, $fields);

I'm able to use it with update_issue and set the fields to a specific value, that works.

Could you please give me an example of $fields to display, for instance, the issue key and the summary using the search_issues method.

Thank you

**Comment by frimicc** [comment]
There was a bug in the custom fields parsing that will be fixed in version 1.7. Try with that version when it is released, soon. Apologies for the long delay.
