### ISSUE TITLE
get_issue_worklogs gives empty result

### ISSUE THREAD

**Issue by mkauzlar** [frimicc/jira-client-automated#15]
Hello I was trying to get worklog data of an issue (ORT-83) but the response is empty.
JIRA version is 6.1.4.

If I try getting the issue details with $jira->get_issue('ORT-83'); it works as expected.
If I try to add a log in the worklog with $jira->add_issue_worklog('ORT-83', $worklog); it works as expected.
But $jira->get_issue_worklogs('ORT-83'); doesn't work

**Comment by frimicc** [comment]
I can't replicate this error. I apologize for the long delay, but if you're still using the module and still having problems after version 1.7 is released (soon), please let me know. I hope to be more responsive in the future.
