### ISSUE TITLE
trouble using get_issue

### ISSUE THREAD

**Issue by kurand** [frimicc/jira-client-automated#17]
Hello. 
When i use method get_issue, I get the following error:
`
Can't use string ("2017-08-14") as a HASH ref while "strict refs" in use at /usr/local/share/perl/5.20.2/JIRA/Client/Automated.pm line 477.
`

Use OS Debian 8
JIRA-Client-Automated - 1.6 version

**Comment by frimicc** [comment]
This is finally being fixed in version 1.7. Sorry for the delay!
