### ISSUE TITLE
createmeta rest endpoint removed

### ISSUE THREAD

**Issue by iamlgh** [frimicc/jira-client-automated#22]
In _issue_type_meta this call no longer works:
`         $uri = "$self->{auth_url}issue/createmeta?projectKeys=${project}&expand=projects.issuetypes.fields";
`
It createmeta was deprecated in Jira 8.4 and removed from Jira 9.0:
https://confluence.atlassian.com/jiracore/createmeta-rest-endpoint-to-be-removed-975040986.html

**Comment by iamlgh** [comment]
I can see this is a duplicate of #21, I guess a new release of the module was never made.

**Comment by frimicc** [comment]
@iamlgh I'm looking for a new maintainer for this module. Would you be interested?
